# Generated by Django 5.2.5 on 2025-08-23 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='meal',
            name='cal_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fat_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='grams',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein_per_100g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='meal',
            name='source_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
