# Generated by Django 5.2.5 on 2025-08-24 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_meal_meal_type_meal_cal_per_100g_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('default_grams', models.FloatField(blank=True, null=True)),
                ('cal_per_100g', models.FloatField(blank=True, null=True)),
                ('protein_per_100g', models.FloatField(blank=True, null=True)),
                ('carbs_per_100g', models.FloatField(blank=True, null=True)),
                ('fat_per_100g', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
