# Generated by Django 5.2.5 on 2025-08-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_favoritefood'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='activity',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly active'), ('moderate', 'Moderately active'), ('active', 'Active'), ('very_active', 'Very active')], default='moderate', max_length=12),
        ),
        migrations.AddField(
            model_name='goal',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='objective',
            field=models.CharField(choices=[('lose', 'Lose fat'), ('maintain', 'Maintain'), ('gain', 'Gain muscle')], default='maintain', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='weekly_rate_kg',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='goal',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
